DROP TABLE IF EXISTS Hotel;
CREATE TABLE Hotel(
     ID     VARCHAR(255) PRIMARY KEY,
     NOME   VARCHAR(255) NOT NULL,
     ENDERECO     VARCHAR(255) NOT NULL,
     AVALIACAO    VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS Endereco;

CREATE TABLE IF NOT EXISTS Endereco(
    RUA    VARCHAR(255) NOT NULL,
    NUMERO   INT NOT NULL,
    CIDADE  VARCHAR(255) NOT NULL,
    ESTADO   VARCHAR(255) NOT NULL
);